### PR TITLE
use css filter to obtain background blur

### PR DESCRIPTION
**Pull request by omsmith**

### CODE REVIEW

**Comment by omsmith** [comment]
That a visual approval as well, or just from ze code?

**Comment by omsmith** [comment]
Uhhh, doesn't quite work in firefox, will have to dig.

**Comment by dlockhart** [comment]
Haha clearly not a visual approval.

**Comment by omsmith** [comment]
Okay so presently this works in Chrome / Firefox (assumedly Safari).

This won't work at all for IE.

Presently isn't working for Edge (Edge bug).

**Comment by dlockhart** [comment]
Looks good in Safari

**Pull request merged**
